apiVersion: v1
kind: Namespace
metadata:
  name: jpa-demo-namespace

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: jpa-demo-namespace
data:
  DB_HOST: mysql-service

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: jpa-demo-namespace
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNA==  # Base64-encoded '1234'
  MYSQL_DATABASE: anBhX2RlbW8=  # Base64-encoded 'jpa_demo'
  MYSQL_USER: anBhX2RlbW9fdXNlcg==  # Base64-encoded 'jpa_demo_user'
  MYSQL_PASSWORD: anBhX2RlbW9fcGFzczE=  # Base64-encoded 'jpa_demo_pass1'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpa-basic-app
  namespace: jpa-demo-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jpa-basic-app
  template:
    metadata:
      labels:
        app: jpa-basic-app
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35
          command: [ 'sh', '-c', 'until nc -z $DB_HOST 3306; do echo waiting for mysql; sleep 3; done;' ]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_HOST
      containers:
        - name: jpa-basic-app
          image: deep52a/jpa-demo-2025:1
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_HOST
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8081
#            initialDelaySeconds: 30
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8081
#            initialDelaySeconds: 30
#            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: jpa-basic-service
  namespace: jpa-demo-namespace
spec:
  selector:
    app: jpa-basic-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: jpa-demo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: mysql-db
          image: mysql:8.4.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
          livenessProbe:
            exec:
              command: [ "mysqladmin", "ping", "-h", "localhost" ]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command: [ "mysqladmin", "ping", "-h", "localhost" ]
            initialDelaySeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: jpa-demo-namespace
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: jpa-demo-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
